# Generated by Django 5.2.7 on 2025-10-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
