# Generated by Django 5.2.7 on 2025-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='message_pdfs/'),
        ),
    ]
