# Generated by Django 5.2.7 on 2025-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_eventinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
