# Generated by Django 5.2.7 on 2025-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_avatar_url_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://zjsarscptztnuqgtesjp.supabase.co/storage/v1/object/public/media/avatars/1_temp/avatar.svg', null=True),
        ),
    ]
