# Generated by Django 5.2.5 on 2025-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='hashtag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='hashtag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
